apiVersion: apps/v1
kind: Deployment
metadata:
  name: godocker-deployment
spec:
  selector:
    matchLabels:
      app: godocker
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: godocker
    spec:
      containers:
      - name: godocker
        image: nivantdot/godocker:1.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 5005
